"""Inclusão de coluna na tabela

Revision ID: 674fcbcc2c89
Revises: 6a5b929d3be3
Create Date: 2026-10-03 23:11:49.879863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674fcbcc2c89'
down_revision = '6a5b929d3be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondido', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('respondido')

    # ### end Alembic commands ###
